Little work on the script

diff --git a/src/main/resources/jongo b/src/main/resources/jongo
--- a/src/main/resources/jongo
+++ b/src/main/resources/jongo
@@ -4,45 +4,46 @@
 # Depends on pkill and bash 4+
 #
 
+if [ "${JAVA_HOME}" == "" ]; then
+    echo "JAVA_HOME Not set. Install the JRE and set the JAVA_HOME in your initialization file"
+    exit 1
+fi
+
+if [ ! -d "${JAVA_HOME}" ] ; then
+    echo "Java ${JAVA_HOME} Directory doesn't exist."
+    exit 1
+else
+    if [ ! -x "${JAVA_HOME}/bin/java" ] ; then
+        echo "Java binary error: not found or not executable"
+        exit 1
+    fi
+fi
+
 do_start () {
-    if [ "${JAVA_HOME}" == "" ]; then
-        echo "JAVA_HOME Not set. Install the JRE and set the JAVA_HOME in your initialization file"
-        exit 1
-    fi
-
-    if [ ! -d "${JAVA_HOME}" ] ; then
-        echo "Java ${JAVA_HOME} Directory doesn't exist."
-        exit 1
-    else
-        if [ ! -x "${JAVA_HOME}/bin/java" ] ; then
-            echo "Java binary error: not found or not executable"
-            exit 1
-        fi
-    fi
-
     local path="lib/*:etc"
     local opts=""
 
-    # Launch the process and save its pid to a file
     local exit_code=10
     while [ $exit_code -eq 10 ]; do
         "${JAVA_HOME}/bin/java" ${opts} -cp "${path}" org.jongo.JongoJetty
         exit_code=$?
     done
-
 }
 
 do_demo () {
     local opts="-Denvironment=demo"
+    local path="lib/*:etc"
+    "${JAVA_HOME}/bin/java" ${opts} -cp "${path}" org.jongo.JongoJetty
 }
 
 do_stop () {
-     pkill -f org.jongo.JongoJetty
+    pkill -f "org.jongo.JongoJetty"
+    exit $?
 }
 
 do_status () {
-    pkill -0 -f org.jongo.JongoJetty > /dev/null 2>&1 && echo "Process is running" && exit 0
-    echo "Jongo is not running"
+    pkill -0 -f "org.jongo.JongoJetty" > /dev/null 2>&1 && echo "Process is running" && exit 0
+    echo "Jongo is not running" && exit 0
 }
 
 case ${1} in
